version: '3'
services:
  juice-shop:
    image: bkimminich/juice-shop
    networks:
      - app-network

  waf:
    image: owasp/modsecurity-crs:nginx
    ports:
      - "8080:80"
    environment:
      - UPSTREAM_HOST=juice-shop
      - UPSTREAM_PORT=3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge